version: '3.7'

volumes:
  peer0.org1.cloudmile.com:

networks:
  cloudmile:
    name: fabric_test
services:
  peer0.org1.cloudmile.com:
    container_name: peer0.org1.cloudmile.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric-gce
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric-gce/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric-gce/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric-gce/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.org1.cloudmile.com
      - CORE_PEER_ADDRESS=localhost:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.cloudmile.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.cloudmile.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.cloudmile.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org1.cloudmile.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric-gce/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.cloudmile.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /root
    command: peer node start
    volumes:
      - ../organizations/peerOrganizations/org1.cloudmile.com/peers/peer0.org1.cloudmile.com:/etc/hyperledger/fabric-gce
      - peer0.org1.cloudmile.com:/var/hyperledger/production
    ports:
    - 7051:7051
    - 9444:9444
    networks:
      - cloudmile

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.4.4
    labels:
      service: hyperledger-fabric-gce
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric-gce/peer
    command: /bin/bash
    volumes:
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric-gce/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric-gce/peer/scripts/
    depends_on:
      - peer0.org1.cloudmile.com
    networks:
      - cloudmile
