OrdererOrgs:
  - Name: Orderer
    Domain: cloudmile.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.cloudmile.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1












