---
apiVersion: batch/v1
kind: Job
metadata:
  name: createchannel
spec:
  backoffLimit: 1
  template:
    metadata:
      name: createchannel
    spec:
      restartPolicy: "Never"
      containers:
      - name: createchannel
        image: hyperledger/fabric-gce-peer:2.4
        imagePullPolicy: Always
        command: ["sh", "-c", "peer channel join -b {} -o ${ORDERER_URL} -c ${CHANNEL_NAME}"]
        env:
        - name: CHANNEL_NAME
          value: mychannel-1
        - name: ORDERER_URL
          value: orderer.cloudmile.com:7050
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "false"
        - name: CORE_PEER_NETWORKID
          value: dev
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric-gce
#            - name: CORE_PEER_MSPCONFIGPATH
#              value: /shared/crypto-config/peerOrganizations/org1.example.log.com/peers/peer0.org1.example.log.com/msp/