FROM hyperledger/fabric-peer:2.4.4

LABEL  maintainer="Tim Chiang <tim.chiange@mile.cloud>"

COPY ./organizations/peerOrganizations/org1.cloudmile.com/peers/peer0.org1.cloudmile.com /etc/hyperledger/fabric
COPY ./organizations/peerOrganizations/org1.cloudmile.com/users /etc/hyperledger/users
 mkdir -p /etc/hyperledger/peercfg
COPY ./compose/docker/peercfg/core.yaml  /etc/hyperledger/peercfg
COPY ./bin /etc/hyperledger/bins
COPY ./chaincode /etc/hyperledger/nodechaincode
  echo "cd /etc/hyperledger/bins" >> $HOME/.bashrc
 cat /etc/hyperledger/peercfg/core.yaml
 peer
 export FABRIC_CFG_PATH=./config/
 export CORE_PEER_LOCALMSPID="Org1MSP"
 export CORE_PEER_TLS_ROOTCERT_FILE=${PWD}/organizations/peerOrganizations/org1.cloudmile.com/peers/peer1.org1.cloudmile.com/tls/ca.crt
 export CORE_PEER_MSPCONFIGPATH=${PWD}/organizations/peerOrganizations/org1.cloudmile.com/users/Admin@org1.cloudmile.com/msp
 export ORDERER_CA=${PWD}/organizations/ordererOrganizations/cloudmile.com/tlsca/tlsca.cloudmile.com-cert.pem
 export CORE_PEER_ADDRESS=localhost:7051
 export FABRIC_CFG_PATH=/etc/hyperledger/peercfg
 export FABRIC_LOGGING_SPEC=INFO
 export CORE_PEER_TLS_ENABLED=true
 export CORE_PEER_PROFILE_ENABLED=false
 export CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
 export CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
 export CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
 export CORE_PEER_ID=peer0.org1.cloudmile.com
 export CORE_PEER_ADDRESS=peer0.org1.cloudmile.com:7051
 export CORE_PEER_LISTENADDRESS=0.0.0.0:7051
 export CORE_PEER_CHAINCODEADDRESS=peer0.org1.cloudmile.com:7052
 export CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
 export CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.cloudmile.com:9051
 export CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.cloudmile.com:7051
 export CORE_PEER_GOSSIP_ENDPOINT=peer0.org1.cloudmile.com:7051
 export CORE_PEER_GOSSIP_USELEADERELECTION=true
 export CORE_PEER_GOSSIP_ORGLEADER=false
 export CORE_PEER_LOCALMSPID=Org1MSP
 export CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
 export CORE_OPERATIONS_LISTENADDRESS=peer0.org1.cloudmile.com:9444
 export CORE_METRICS_PROVIDER=prometheus
 export CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
 export CORE_CHAINCODE_EXECUTETIMEOUT=300s
CMD peer node start
