apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer
  labels:
    app: peer0-org1
spec:
  serviceName: peer0-org1
  replicas: 1
  selector:
    matchLabels:
      app: peer0-org1
  template:
    metadata:
      labels:
        app: peer0-org1
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
          - "foo.local"
          - "bar.local"
      - ip: "10.1.2.3"
        hostnames:
          - "foo.remote"
          - "bar.remote"
      containers:
      - name: peer0-org1
        image: hyperledger/fabric-gce-pee r:2.4.4
#        command: [ "sh", "-c", "peer channel join -b channel/mychannel-1.block"]
        env:
          - name: FABRIC_CFG_PATH
            value: /etc/hyperledger/peercfg
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: FABRIC_LOGGING_SPEC
            value: INFO
          - name: CORE_PEER_TLS_CERT_FILE
            value: /etc/hyperledger/organizations/peerOrganizations/org1.cloudmile.com/peers/peer0.org1.cloudmile.com/tls/server.crt
          - name: CORE_PEER_TLS_KEY_FILE
            value: /etc/hyperledger/organizations/peerOrganizations/org1.cloudmile.com/peers/peer0.org1.cloudmile.com/tls/server.key
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: /etc/hyperledger/organizations/peerOrganizations/org1.cloudmile.com/peers/peer0.org1.cloudmile.com/tls/ca.crt
          - name: CORE_PEER_ID
            value: peer0.org1.cloudmile.com
          - name: CORE_PEER_ADDRESS
            value: peer0.org1.cloudmile.com:7051
          - name: CORE_PEER_LISTENADDRESS
            value: 0.0.0.0:7051
          - name: CORE_PEER_CHAINCODEADDRESS
            value: peer0.org1.cloudmile.com:7052
          - name: CORE_PEER_CHAINCODELISTENADDRESS
            value: 0.0.0.0:7052
          - name: CORE_PEER_GOSSIP_BOOTSTRAP
            value: peer1.org1.cloudmile.com:9051
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: peer0.org1.cloudmile.com:7051
          - name: CORE_PEER_LOCALMSPID
            value: Org1MSP
          - name: CORE_PEER_MSPCONFIGPATH
            value: /etc/hyperledger/organizations/peerOrganizations/org1.cloudmile.com/peers/peer0.org1.cloudmile.com/msp
          - name: CORE_OPERATIONS_LISTENADDRESS
            value: 0.0.0.0:9444
          - name: CORE_METRICS_PROVIDER
            value: prometheus
          - name: CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG
            value: "{'peername':'peer0org1'}"
          - name: CORE_CHAINCODE_EXECUTETIMEOUT
            value: 300s
          - name: ORDERER_CA
            value: /etc/hyperledger/organizations/ordererOrganizations/cloudmile.com/tlsca/tlsca.cloudmile.com-cert.pem
        volumeMounts:
        - name: chaincode-folder
          mountPath: /etc/hyperledger/chaincode
        - name: peer0-ledger
          mountPath: /var/ledger
        - name: all-tls
          mountPath: /etc/hyperledger/organizations/
        - name: channel-artifacts
          mountPath: /etc/hyperledger/channel
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: core-file
          mountPath: /etc/hyperledger/peercfg
      volumes:
      - name: chaincode-folder
        hostPath:
          path: /home/tim_chiang/chaincode/
      - name: all-tls
        hostPath:
          path: /home/tim_chiang/organizations/
      - name: core-file
        hostPath:
          path: /home/tim_chiang/peercfg
      - name: channel-artifacts
        hostPath:
          path: /home/tim_chiang/channel-artifacts
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
  volumeClaimTemplates:
  - metadata:
      name: peer0-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: general
      resources:
        requests:
          storage: 1Gi
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: peer0-org1-clusterip
#spec:
#  selector:
#    app: peer0-org1
#  ports:
#    - name: peer0-org1-ip-clusterip
#      port: 30751
#    - name: peer0-org1-ip-core
#      port: 30752
#    - name: peer0-org1-ip-chaincode
#      port: 30951
#  type: ClusterIP
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: peer0-org1-nodeport
#spec:
#  selector:
#    app: peer0-org1
#  ports:
#    - name: peer0-org1-ip
#      port: 30751
#      nodePort: 30751
#    - name: peer0-org1-core
#      port: 30752
#      nodePort: 30752
#    - name: peer0-org1-chaincode
#      port: 30951
#      nodePort: 30951
#
#  type: NodePort