OrdererOrgs:
  - Name: Orderer
    Domain: cloudmile.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - "*"
          - "10.10.0.16"
PeerOrgs:
  - Name: Org1
    Domain: org1.cloudmile.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - "*"
        - "10.10.0.9"
    Users:
      Count: 1